const express = require('express');
const session = require('express-session');
const bcrypt = require('bcryptjs');
const Database = require('better-sqlite3');

const app = express();
app.set('trust proxy', 1);

// Railway volumes expose RAILWAY_VOLUME_MOUNT_PATH at runtime.
// Persist the SQLite database there in production; fall back to ./cargex.db locally.
const dataDir = process.env.CARGEX_DATA_DIR || process.env.RAILWAY_VOLUME_MOUNT_PATH || process.cwd();
const db = new Database(require('path').join(dataDir, 'cargex.db'));

app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.get('/health', (req,res)=>res.json({ok:true,app:'CargeX',environment:process.env.NODE_ENV||'development'}));
app.use(session({
  secret: process.env.SESSION_SECRET || 'change-this-secret-before-production',
  resave: false,
  saveUninitialized: false,
  cookie: { httpOnly: true, secure: process.env.NODE_ENV === 'production', sameSite: 'lax', maxAge: 86400000 }
}));

if (process.env.NODE_ENV === 'production' && (!process.env.SESSION_SECRET || process.env.SESSION_SECRET.length < 32)) {
  throw new Error('SESSION_SECRET must be set to a strong value (32+ characters) in production.');
}

const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const statuses = ['Shipment Created','Picked Up','In Transit','Arrived at Facility','Out for Delivery','Delivered','Exception'];
const icons = { 'Shipment Created':'✓','Picked Up':'✓','In Transit':'✓','Arrived at Facility':'●','Out for Delivery':'○','Delivered':'✓','Exception':'!' };

const css = `
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
:root{--blue:#0757d8;--blue2:#0a78e8;--navy:#082b57;--ink:#102a43;--muted:#60738a;--line:#dfe8f3;--bg:#f4f8fc;--green:#10a85a;--shadow:0 18px 45px rgba(12,55,105,.12)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,Arial,sans-serif;color:var(--ink);background:var(--bg)}a{color:inherit;text-decoration:none}button,.btn{font:inherit;cursor:pointer;border:0}.shell{max-width:1240px;margin:auto;padding:0 24px}
.topbar{background:#fff;border-bottom:1px solid #e8eef6}.nav{height:82px;display:flex;align-items:center;justify-content:space-between;gap:25px}.logo{display:flex;align-items:center;gap:11px;font-weight:800;font-size:29px;letter-spacing:-1.2px;color:var(--blue)}.logo-mark{width:46px;height:40px;position:relative}.logo-mark i{display:block;position:absolute;background:var(--blue);height:7px;transform:skewX(-28deg);border-radius:2px}.logo-mark i:nth-child(1){width:39px;top:2px;left:4px}.logo-mark i:nth-child(2){width:31px;top:14px;left:0}.logo-mark i:nth-child(3){width:22px;top:26px;left:9px}.tagline{display:block;color:#183d68;font-size:10px;letter-spacing:2px;margin-top:-2px;font-weight:600}.brand-wrap{line-height:1}.links{display:flex;align-items:center;gap:28px;font-size:14px;font-weight:600;color:#233f61}.links a:hover{color:var(--blue)}.quote{background:var(--blue);color:#fff;padding:13px 20px;border-radius:8px;box-shadow:0 8px 18px rgba(7,87,216,.22)}
.hero{position:relative;overflow:hidden;background:linear-gradient(112deg,#062d5b 0%,#0757d8 55%,#16a7f2 100%);color:#fff}.hero:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 72% 35%,rgba(255,255,255,.18),transparent 25%),linear-gradient(125deg,transparent 50%,rgba(255,255,255,.06) 50%)}.hero-inner{min-height:510px;display:grid;grid-template-columns:1fr 1.1fr;align-items:center;gap:35px;position:relative}.hero h1{font-size:56px;line-height:1.03;margin:0 0 18px;letter-spacing:-2.5px}.hero h1 span{color:#48c7ff}.hero p{font-size:17px;line-height:1.65;max-width:560px;color:#e9f6ff;margin-bottom:26px}.perks{display:flex;gap:20px;flex-wrap:wrap;margin-top:25px}.perk{display:flex;align-items:center;gap:9px;font-size:12px;border-right:1px solid rgba(255,255,255,.35);padding-right:18px}.perk:last-child{border:0}.perk b{display:block;font-size:13px}.perk small{opacity:.8}.track-box{background:#fff;color:var(--ink);border-radius:16px;padding:27px;box-shadow:0 25px 65px rgba(0,24,70,.3);position:relative;z-index:2}.track-box h2{font-size:23px;margin:0 0 6px}.track-box p{color:var(--muted);font-size:13px;margin:0 0 18px}.track-form{display:flex;gap:10px}.track-form input{flex:1}.input{width:100%;padding:15px 16px;border:1px solid #cdd9e8;border-radius:9px;outline:0;font-size:14px;background:#fff}.input:focus{border-color:var(--blue);box-shadow:0 0 0 3px rgba(7,87,216,.1)}.primary{background:var(--blue);color:#fff;padding:14px 20px;border-radius:9px;font-weight:700;box-shadow:0 8px 20px rgba(7,87,216,.2)}.primary:hover{background:#0048bd}.visual{position:absolute;right:-15px;bottom:-10px;width:62%;height:235px;pointer-events:none}.road{position:absolute;left:0;right:0;bottom:20px;height:7px;background:rgba(255,255,255,.35);border-radius:20px}.truck{position:absolute;right:8%;bottom:27px;width:280px;height:105px}.truck-body{position:absolute;left:0;bottom:20px;width:190px;height:70px;background:#fff;border-radius:8px 3px 3px 8px;box-shadow:0 9px 18px rgba(0,0,0,.15)}.truck-body:before{content:'CargeX';position:absolute;left:35px;top:24px;color:var(--blue);font-weight:800;font-size:23px}.truck-cab{position:absolute;right:0;bottom:20px;width:78px;height:57px;background:#e9f5ff;border-radius:4px 16px 4px 4px;border-left:7px solid #fff}.truck-window{position:absolute;right:9px;top:9px;width:47px;height:22px;background:#b5dcf7;border-radius:3px}.wheel{position:absolute;bottom:2px;width:34px;height:34px;border-radius:50%;background:#09294c;border:8px solid #fff;box-shadow:0 0 0 2px #09294c}.w1{left:30px}.w2{right:25px}
.section{padding:64px 0}.section-head{text-align:left;margin-bottom:30px}.section-head h2{font-size:30px;margin:0 0 8px}.section-head .rule{width:48px;height:4px;background:var(--blue);border-radius:4px}.services{display:grid;grid-template-columns:repeat(5,1fr);background:#fff;border-radius:15px;box-shadow:var(--shadow);overflow:hidden}.service{padding:30px 23px;border-right:1px solid var(--line)}.service:last-child{border:0}.service-icon{width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:#e9f4ff;color:var(--blue);font-size:23px;margin-bottom:18px}.service h3{font-size:15px;margin:0 0 10px}.service p{font-size:12px;color:var(--muted);line-height:1.6;min-height:57px}.learn{color:var(--blue);font-weight:700;font-size:12px}.why{background:#eaf4fc}.why-grid{display:grid;grid-template-columns:1.1fr 1fr;align-items:center;gap:55px}.delivery-art{min-height:300px;border-radius:20px;background:linear-gradient(135deg,#0a65df,#78d5ff);position:relative;overflow:hidden;box-shadow:var(--shadow)}.delivery-art:after{content:'CargeX';position:absolute;right:28px;top:35px;color:#fff;font-size:42px;font-weight:800;opacity:.18}.person{position:absolute;left:23%;bottom:0;width:120px;height:210px;background:#fff;border-radius:70px 70px 20px 20px}.person:before{content:'';position:absolute;left:34px;top:-48px;width:52px;height:52px;border-radius:50%;background:#8a5a3c}.box{position:absolute;left:52%;bottom:34px;width:120px;height:95px;background:#d7a46d;transform:rotate(-4deg);box-shadow:0 12px 20px rgba(0,0,0,.18)}.why h2{font-size:31px;margin:0 0 9px}.why p{color:var(--muted);line-height:1.6}.features{display:grid;grid-template-columns:repeat(2,1fr);gap:22px;margin-top:28px}.feature{display:flex;gap:12px}.feature-icon{width:42px;height:42px;border-radius:50%;background:#fff;color:var(--blue);display:grid;place-items:center;flex:none;box-shadow:0 6px 18px rgba(8,65,130,.08)}.feature h4{margin:0 0 4px;font-size:14px}.feature small{color:var(--muted);font-size:11px;line-height:1.5}
.page{padding:45px 0 70px}.card{background:#fff;border-radius:15px;padding:28px;box-shadow:var(--shadow);margin-bottom:22px}.page-title h1{margin:0 0 7px;font-size:36px}.muted{color:var(--muted)}.error{color:#9b1c1c;background:#fff0f0;padding:12px 14px;border-radius:9px;margin:15px 0}.success{color:#146b3a;background:#e9fbf1;padding:12px 14px;border-radius:9px;margin:15px 0}.result-head{display:flex;justify-content:space-between;align-items:center;gap:20px}.status{display:inline-flex;padding:7px 11px;border-radius:999px;background:#e5f8ed;color:#08753d;font-size:12px;font-weight:800}.meta-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:20px 0;margin:20px 0}.meta b{display:block;font-size:11px;color:var(--muted);margin-bottom:5px;text-transform:uppercase;letter-spacing:.6px}.meta span{font-size:14px;font-weight:600}.timeline{position:relative;margin:25px 0 5px;padding-left:30px}.timeline:before{content:'';position:absolute;left:9px;top:5px;bottom:5px;width:2px;background:#dce6f0}.event{position:relative;padding-bottom:25px}.dot{position:absolute;left:-27px;top:0;width:18px;height:18px;border-radius:50%;background:#fff;border:2px solid #cbd7e5;color:#9baabd;font-size:9px;display:grid;place-items:center}.event.current .dot{border-color:var(--blue);background:var(--blue);color:#fff}.event.done .dot{border-color:var(--green);background:var(--green);color:#fff}.event h4{margin:0 0 4px;font-size:14px}.event small{color:var(--muted)}.event p{margin:5px 0 0;color:#41566e;font-size:12px}.estimate{background:#eaf5ff;padding:17px;border-radius:10px;color:var(--blue);font-weight:700}
.admin-head{display:flex;justify-content:space-between;align-items:center;gap:15px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.field label{display:block;font-size:12px;font-weight:700;margin-bottom:7px;color:#304c6d}textarea.input{min-height:90px;resize:vertical}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:14px 10px;text-align:left;border-bottom:1px solid var(--line)}th{color:var(--muted);font-size:11px;text-transform:uppercase}.table-wrap{overflow:auto}.secondary{background:#edf3fa;color:var(--ink);padding:10px 14px;border-radius:8px;font-weight:700;font-size:12px}.footer{background:#082b57;color:#d9e8f7;padding:35px 0}.footer-grid{display:flex;justify-content:space-between;align-items:center;gap:25px}.footer .logo{color:#fff}.footer small{color:#a8bfd8}.footer-links{display:flex;gap:18px;font-size:12px}
@media(max-width:950px){.links{display:none}.hero-inner{grid-template-columns:1fr;padding-top:60px;padding-bottom:40px}.visual{display:none}.services{grid-template-columns:repeat(2,1fr)}.service:nth-child(2n){border-right:0}.why-grid{grid-template-columns:1fr}.meta-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:620px){.shell{padding:0 16px}.nav{height:70px}.logo{font-size:24px}.hero h1{font-size:42px}.track-form{flex-direction:column}.services{grid-template-columns:1fr}.service{border-right:0;border-bottom:1px solid var(--line)}.grid{grid-template-columns:1fr}.footer-grid{flex-direction:column;align-items:flex-start}.features{grid-template-columns:1fr}.meta-grid{grid-template-columns:1fr}.result-head{align-items:flex-start;flex-direction:column}}
`;

function header(active='') { return `<header class="topbar"><div class="shell nav"><a class="logo" href="/"><span class="logo-mark"><i></i><i></i><i></i></span><span class="brand-wrap">CargeX<span class="tagline">FASTER · SAFER · FURTHER</span></span></a><nav class="links"><a href="/" class="${active==='home'?'active':''}">Home</a><a href="/track">Track Shipment</a><a href="/#services">Services</a><a href="/#about">About Us</a><a href="/#contact">Contact</a><a href="/admin">Admin</a><a class="quote" href="mailto:support@cargex.com">Get a Quote</a></nav></div></header>`; }
function footer(){return `<footer class="footer"><div class="shell footer-grid"><a class="logo" href="/"><span class="logo-mark"><i></i><i></i><i></i></span><span class="brand-wrap">CargeX<span class="tagline" style="color:#d9e8f7">FASTER · SAFER · FURTHER</span></span></a><div class="footer-links"><a href="/">Home</a><a href="/track">Track</a><a href="/#services">Services</a><a href="/#contact">Contact</a></div><small>© ${new Date().getFullYear()} CargeX. All rights reserved.</small></div></footer>`; }
function layout(title,body,active=''){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="CargeX — fast, secure and reliable delivery tracking."><title>${esc(title)} | CargeX</title><style>${css}</style></head><body>${header(active)}${body}${footer()}</body></html>`}

function init(){
 db.exec(`CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY,email TEXT UNIQUE,password TEXT);CREATE TABLE IF NOT EXISTS shipments(id INTEGER PRIMARY KEY,tracking_no TEXT UNIQUE,customer TEXT,origin TEXT,destination TEXT,package_desc TEXT,status TEXT,estimated_delivery TEXT,created_at TEXT);CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,shipment_id INTEGER,status TEXT,location TEXT,note TEXT,created_at TEXT)`);
 const a=db.prepare('SELECT COUNT(*) c FROM admins').get();
 if(!a.c) db.prepare('INSERT INTO admins(email,password) VALUES(?,?)').run('admin@cargex.com',bcrypt.hashSync('ChangeMe123!',10));
}
init();

app.get('/',(req,res)=>res.send(layout('Home',`<main>
<section class="hero"><div class="shell hero-inner"><div><h1>Your World,<br><span>Delivered.</span></h1><p>CargeX provides fast, secure and reliable delivery solutions for individuals and businesses, locally and globally.</p><a class="primary" href="/track">Track a Shipment →</a><div class="perks"><div class="perk">🛡️ <span><b>Safe & Secure</b><small>Delivery</small></span></div><div class="perk">◷ <span><b>On-Time</b><small>Delivery</small></span></div><div class="perk">◎ <span><b>Global</b><small>Coverage</small></span></div><div class="perk">◉ <span><b>24/7</b><small>Support</small></span></div></div></div><div class="track-box"><h2>Track Your Shipment</h2><p>Enter your CargeX tracking number to get the latest shipment updates.</p><form class="track-form" method="get" action="/track"><input class="input" name="number" placeholder="e.g. CARGEX-2026-000123" required><button class="primary">⌕ &nbsp;Track</button></form><div class="visual"><div class="road"></div><div class="truck"><div class="truck-body"></div><div class="truck-cab"><div class="truck-window"></div></div><div class="wheel w1"></div><div class="wheel w2"></div></div></div></div></div></section>
<section class="section" id="services"><div class="shell"><div class="section-head"><h2>Our Services</h2><div class="rule"></div></div><div class="services"><div class="service"><div class="service-icon">▣</div><h3>Domestic Delivery</h3><p>Fast and reliable delivery across your country.</p><a class="learn" href="mailto:support@cargex.com">Learn More →</a></div><div class="service"><div class="service-icon">◎</div><h3>International Shipping</h3><p>Connect your business to destinations around the world.</p><a class="learn" href="mailto:support@cargex.com">Learn More →</a></div><div class="service"><div class="service-icon">ϟ</div><h3>Express Delivery</h3><p>When speed matters most, choose express handling.</p><a class="learn" href="mailto:support@cargex.com">Learn More →</a></div><div class="service"><div class="service-icon">▱</div><h3>E-commerce Solutions</h3><p>Powering your online business with dependable delivery.</p><a class="learn" href="mailto:support@cargex.com">Learn More →</a></div><div class="service"><div class="service-icon">⚓</div><h3>Logistics & Freight</h3><p>Flexible and scalable supply-chain solutions.</p><a class="learn" href="mailto:support@cargex.com">Learn More →</a></div></div></div></section>
<section class="section why" id="about"><div class="shell why-grid"><div class="delivery-art"><div class="person"></div><div class="box"></div></div><div><h2>Why Choose CargeX?</h2><p>We go the extra mile to make your delivery experience seamless, transparent and dependable.</p><div class="features"><div class="feature"><div class="feature-icon">⌖</div><div><h4>Real-Time Tracking</h4><small>Track your shipment at every step.</small></div></div><div class="feature"><div class="feature-icon">◎</div><div><h4>Global Network</h4><small>Reach more destinations with CargeX.</small></div></div><div class="feature"><div class="feature-icon">✓</div><div><h4>Trusted & Secure</h4><small>Your packages are handled with care.</small></div></div><div class="feature"><div class="feature-icon">◉</div><div><h4>Dedicated Support</h4><small>Our team is ready to help.</small></div></div></div></div></div></section>
<section class="section" id="contact"><div class="shell"><div class="card" style="text-align:center"><h2>Ready to ship?</h2><p class="muted">Talk to CargeX about your next delivery.</p><a class="primary" href="mailto:support@cargex.com">Contact CargeX</a></div></div></section>
</main>`,'home')));

app.get('/track',(req,res)=>{
 let result='';
 if(req.query.number){const number=String(req.query.number).trim().toUpperCase();const s=db.prepare('SELECT * FROM shipments WHERE tracking_no=?').get(number);if(!s)result=`<div class="card"><div class="error">No shipment was found for tracking number <b>${esc(number)}</b>. Please check the number and try again.</div></div>`;else{const ev=db.prepare('SELECT * FROM events WHERE shipment_id=? ORDER BY id DESC').all(s.id);result=`<div class="card"><div class="result-head"><div><div class="muted" style="font-size:12px">TRACKING NUMBER</div><h2 style="margin:5px 0">${esc(s.tracking_no)}</h2></div><span class="status">${esc(s.status)}</span></div><div class="meta-grid"><div class="meta"><b>Customer</b><span>${esc(s.customer)}</span></div><div class="meta"><b>From</b><span>${esc(s.origin)}</span></div><div class="meta"><b>Destination</b><span>${esc(s.destination)}</span></div><div class="meta"><b>Estimated Delivery</b><span>${esc(s.estimated_delivery||'To be confirmed')}</span></div></div><h3>Shipment Progress</h3><div class="timeline">${ev.map((e,i)=>`<div class="event ${i===0?'current ':''}${e.status==='Delivered'?'done':''}"><div class="dot">${icons[e.status]||'•'}</div><h4>${esc(e.status)}</h4><small>${esc(e.location||'')} · ${esc(e.created_at)}</small>${e.note?`<p>${esc(e.note)}</p>`:''}</div>`).join('')}</div>${s.estimated_delivery?`<div class="estimate">🚚 &nbsp; Estimated delivery: ${esc(s.estimated_delivery)}</div>`:''}</div>`}}
 res.send(layout('Track Shipment',`<main class="page"><div class="shell"><div class="page-title"><h1>Track Your Shipment</h1><p class="muted">Enter your CargeX tracking number for the latest delivery status.</p></div><div class="card"><form class="track-form" method="get"><input class="input" name="number" value="${esc(req.query.number||'')}" placeholder="Enter tracking number e.g. CARGEX-2026-000001" required><button class="primary">⌕ &nbsp;Track Shipment</button></form></div>${result}</div></main>`));
});

function auth(req,res,next){if(!req.session.admin)return res.redirect('/admin/login');next();}
app.get('/admin/login',(req,res)=>res.send(layout('Admin Login',`<main class="page"><div class="shell" style="max-width:620px"><div class="card"><h1>Admin Portal</h1><p class="muted">Manage CargeX shipments and publish tracking updates.</p>${req.query.error?'<div class="error">Invalid email or password.</div>':''}<form method="post" action="/admin/login"><div class="field"><label>Email</label><input class="input" type="email" name="email" required></div><div class="field"><label>Password</label><input class="input" type="password" name="password" required></div><button class="primary">Sign in</button></form><p class="muted" style="font-size:11px;margin-top:20px">Default first-login account: admin@cargex.com / ChangeMe123! — change it before production.</p></div></div></main>`)));
app.post('/admin/login',(req,res)=>{const a=db.prepare('SELECT * FROM admins WHERE email=?').get(req.body.email);if(a&&bcrypt.compareSync(req.body.password,a.password)){req.session.admin={id:a.id,email:a.email};return res.redirect('/admin')}res.redirect('/admin/login?error=1')});
app.get('/admin/account',auth,(req,res)=>res.send(layout('Admin Account',`<main class="page"><div class="shell" style="max-width:700px"><div class="card"><h1>Admin Account</h1><p class="muted">Change the administrator password before using CargeX in production.</p>${req.query.error?'<div class="error">'+esc(req.query.error)+'</div>':''}${req.query.success?'<div class="success">Password updated successfully.</div>':''}<form method="post" action="/admin/account/password"><div class="field"><label>Current password</label><input class="input" type="password" name="current_password" required></div><div class="field"><label>New password</label><input class="input" type="password" name="new_password" minlength="12" required></div><div class="field"><label>Confirm new password</label><input class="input" type="password" name="confirm_password" minlength="12" required></div><button class="primary">Change Password</button></form><p style="margin-top:20px"><a class="learn" href="/admin">← Back to dashboard</a></p></div></div></main>`)));
app.post('/admin/account/password',auth,(req,res)=>{const a=db.prepare('SELECT * FROM admins WHERE id=?').get(req.session.admin.id);if(!a||!bcrypt.compareSync(req.body.current_password||'',a.password))return res.redirect('/admin/account?error=Current%20password%20is%20incorrect');const next=String(req.body.new_password||'');if(next.length<12)return res.redirect('/admin/account?error=New%20password%20must%20be%20at%20least%2012%20characters');if(next!==String(req.body.confirm_password||''))return res.redirect('/admin/account?error=New%20passwords%20do%20not%20match');db.prepare('UPDATE admins SET password=? WHERE id=?').run(bcrypt.hashSync(next,12),a.id);res.redirect('/admin/account?success=1')});
app.post('/admin/logout',(req,res)=>req.session.destroy(()=>res.redirect('/')));
app.get('/admin',auth,(req,res)=>{const ss=db.prepare('SELECT * FROM shipments ORDER BY id DESC').all();res.send(layout('Admin Dashboard',`<main class="page"><div class="shell"><div class="admin-head"><div><h1>Admin Dashboard</h1><p class="muted">Create shipments and keep customers informed.</p></div><div style="display:flex;gap:8px"><a class="secondary" href="/admin/account">Account</a><form method="post" action="/admin/logout"><button class="secondary">Log out</button></form></div></div><div class="card"><h2>Create Shipment</h2><form method="post" action="/admin/shipments"><div class="grid"><div class="field"><label>Customer</label><input class="input" name="customer" required></div><div class="field"><label>Origin</label><input class="input" name="origin" required></div><div class="field"><label>Destination</label><input class="input" name="destination" required></div><div class="field"><label>Estimated delivery</label><input class="input" type="date" name="estimated_delivery"></div></div><div class="field"><label>Package description</label><input class="input" name="package_desc" placeholder="Documents, parcel, etc."></div><button class="primary">Create & Generate Tracking Number</button></form></div><div class="card"><h2>Shipments</h2><div class="table-wrap"><table><tr><th>Tracking</th><th>Customer</th><th>Destination</th><th>Status</th><th></th></tr>${ss.map(s=>`<tr><td><b>${esc(s.tracking_no)}</b></td><td>${esc(s.customer)}</td><td>${esc(s.destination)}</td><td><span class="status">${esc(s.status)}</span></td><td><a class="secondary" href="/admin/shipments/${s.id}">Manage</a></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No shipments yet.</td></tr>'}</table></div></div></div></main>`));});
app.post('/admin/shipments',auth,(req,res)=>{const count=db.prepare('SELECT COUNT(*) c FROM shipments').get().c||0;const n='CARGEX-'+new Date().getFullYear()+'-'+String(count+1).padStart(6,'0')+'-'+Math.random().toString(36).slice(2,6).toUpperCase();const now=new Date().toISOString().slice(0,16).replace('T',' ');const r=db.prepare('INSERT INTO shipments(tracking_no,customer,origin,destination,package_desc,status,estimated_delivery,created_at) VALUES(?,?,?,?,?,?,?,?)').run(n,req.body.customer,req.body.origin,req.body.destination,req.body.package_desc||'','Shipment Created',req.body.estimated_delivery||'',now);db.prepare('INSERT INTO events(shipment_id,status,location,note,created_at) VALUES(?,?,?,?,?)').run(r.lastInsertRowid,'Shipment Created',req.body.origin,'Shipment record created.',now);res.redirect('/admin/shipments/'+r.lastInsertRowid)});
app.get('/admin/shipments/:id',auth,(req,res)=>{const s=db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id);if(!s)return res.status(404).send('Not found');const ev=db.prepare('SELECT * FROM events WHERE shipment_id=? ORDER BY id DESC').all(s.id);res.send(layout('Manage Shipment',`<main class="page"><div class="shell"><a class="learn" href="/admin">← Dashboard</a><div class="card"><div class="result-head"><div><div class="muted" style="font-size:12px">TRACKING NUMBER</div><h1 style="margin:5px 0">${esc(s.tracking_no)}</h1></div><span class="status">${esc(s.status)}</span></div><div class="meta-grid"><div class="meta"><b>Customer</b><span>${esc(s.customer)}</span></div><div class="meta"><b>Route</b><span>${esc(s.origin)} → ${esc(s.destination)}</span></div><div class="meta"><b>Package</b><span>${esc(s.package_desc||'—')}</span></div><div class="meta"><b>Estimated</b><span>${esc(s.estimated_delivery||'—')}</span></div></div></div><div class="card"><h2>Publish Tracking Update</h2><form method="post" action="/admin/shipments/${s.id}/events"><div class="grid"><div class="field"><label>Status</label><select class="input" name="status">${statuses.map(x=>`<option ${x===s.status?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Location</label><input class="input" name="location" required></div></div><div class="field"><label>Customer note</label><textarea class="input" name="note" placeholder="Optional message about this update"></textarea></div><button class="primary">Publish Update</button></form></div><div class="card"><h2>Shipment History</h2><div class="timeline">${ev.map((e,i)=>`<div class="event ${i===0?'current ':''}${e.status==='Delivered'?'done':''}"><div class="dot">${icons[e.status]||'•'}</div><h4>${esc(e.status)}</h4><small>${esc(e.location||'')} · ${esc(e.created_at)}</small>${e.note?`<p>${esc(e.note)}</p>`:''}</div>`).join('')}</div></div></div></main>`));});
app.post('/admin/shipments/:id/events',auth,(req,res)=>{const s=db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id);if(!s)return res.sendStatus(404);if(!statuses.includes(req.body.status))return res.status(400).send('Invalid status');const now=new Date().toISOString().slice(0,16).replace('T',' ');db.prepare('UPDATE shipments SET status=? WHERE id=?').run(req.body.status,s.id);db.prepare('INSERT INTO events(shipment_id,status,location,note,created_at) VALUES(?,?,?,?,?)').run(s.id,req.body.status,req.body.location,req.body.note||'',now);res.redirect('/admin/shipments/'+s.id)});

const port=process.env.PORT||3000;app.listen(port,()=>console.log('CargeX running on http://localhost:'+port));
